sportsnewsapp/urls.py
from django.urls import path
from .views import *

app_name = 'sportsnewsapp'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('categorydetail/<int:pk>/',
         CategoryDetailView.as_view(), name='categorydetail'),
    path('newsdetail/<int:pk>/',
         NewsDetailView.as_view(), name='newsdetail'),
    path('newscommentcreate/<int:pk>/',
         NewsCommentCreateView.as_view(),
         name='newscommentcreate'),
]

sportsnewsproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sportsnewsapp.urls', namespace='sportsnewsapp')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sportsnewsapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        abstract = True

    def delete(self):
        self.deleted_at = timezone.now()
        super().save()


class Category(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='category/')

    def __str__(self):
        return self.title


class News(TimeStamp):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='allnews')
    content = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='news/')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    viewed = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.title


class Comment(TimeStamp):
    post = models.ForeignKey(
        News, on_delete=models.CASCADE, related_name='comments')
    comment = models.TextField()
    commentername = models.CharField(max_length=200)
    email = models.EmailField()

    def __str__(self):
        return self.commentername + "comment on " + self.post.title

sportsnewsapp/forms.py
from django import forms
from .models import *


class NewsCommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Write your comment...'
    }))
    commentername = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Name...'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Enter your valid email...'
    }))

sportsnewsapp/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.views.generic import *
from .models import *
from .forms import *
import urllib.request
# import json
# with urllib.request.urlopen("http://api.openweathermap.org/data/2.5/weather?q=Kathmandu&APPID=58fb41d9334be75766dc0684f60fff2f") as url:
#     temp = json.loads(url.read().decode())

#     temp = int(temp['main']['temp'] - 273)


class ClientMixin(object):
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        # context['temp'] = temp
        context['latestnews'] = News.objects.filter(
            deleted_at__isnull=True).order_by('-id')
        context['categories'] = Category.objects.filter(
            deleted_at__isnull=True)
        context['comments'] = Comment.objects.filter(
            deleted_at__isnull=True).order_by('-id')
        context['breaking_news'] = News.objects.filter(
            deleted_at__isnull=True,
            category__title='Breaking News').order_by('-id')
        return context


class HomeView(ClientMixin, TemplateView):
    template_name = 'clienttemplates/home.html'


class NewsDetailView(ClientMixin, DetailView):
    template_name = 'clienttemplates/newsdetail.html'
    model = News
    context_object_name = 'news'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.id = self.kwargs['pk']
        news = News.objects.get(id=self.id)
        viewcount = news.viewed + 1
        news.viewed = viewcount
        news.save()
        context['form'] = NewsCommentForm
        return context

    # def get(self, request, *args, **kwargs):
    #     self.id = self.kwargs['pk']
    #     news = News.objects.get(id=self.id)
    #     viewcount = news.viewed + 1
    #     news.viewed = viewcount
    #     news.save()
    #     return super().get(request, *args, **kwargs)


class CategoryDetailView(ClientMixin, DetailView):
    template_name = 'clienttemplates/categorydetail.html'
    model = Category
    context_object_name = 'category'


class NewsCommentCreateView(SuccessMessageMixin, ClientMixin, FormView):
    template_name = 'clienttemplates/newsdetail.html'
    form_class = NewsCommentForm
    success_url = '/'
    success_message = 'Thank you for creating waiyati comment here. '

    def dispatch(self, *args, **kwargs):
        self.id = self.kwargs['pk']
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        self.comment = form.cleaned_data['comment']
        self.commentername = form.cleaned_data['commentername']
        self.news = News.objects.get(id=self.id)
        Comment.objects.create(post=self.news, comment=self.comment,
                               commentername=self.commentername)

        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        url = '/newsdetail/' + str(self.id)
        return url

templates/clienttemplates/categorydetail.html
{% extends 'clienttemplates/base.html' %}

{% load static %}

{% block content %}

<section class="p-heading text-center">
        	<div class="container">
        		<div class="page-bg">
        			<div class="row">
        				<div class="col-md-12">
        					<div class="p-content">
        						<h4>CATAGORY</h4>
        						<ul class="list-unstyled list-inline">
        							<li class="list-inline-item"><a href="{% url 'sportsnewsapp:home' %}">Home</a></li>
        							<li class="list-inline-item"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>{{category.title}}</li>
        						</ul>
        					</div>
        				</div>
        			</div>
        		</div>
        	</div>
        </section>

<section class="catagory">
        	<div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-12">
                    	{% for news in category.allnews.all %}
                        <div class="catagory-content">
                            <div class="cat-img">
                                <a href="#"><img src="{{news.image.url}}" alt="" class="img-fluid" style="max-width: 260px!important; "></a>
                            </div>
                            <div class="img-content">
                                <h6><a href="#">{{news.title|truncatechars:"50"}}</a></h6>
                                <ul class="list-unstyled list-inline">
                                    <li class="list-inline-item">{{news.category}}</li>
                                    <li class="list-inline-item">{{news.created_at.date}}</li>
                                </ul>
                                <p>{{news.content|safe|truncatewords:"25"}} <a class="btn btn-default"  href="{% url 'sportsnewsapp:newsdetail' news.id %}">Read More....</a></p>
                            </div>
                        </div>
                        {% endfor %}

                        <div class="pagi">
                            <ul class="list-unstyled list-inline">
                                <li class="list-inline-item active"><a href="#">1</a></li>
                                <li class="list-inline-item"><a href="#">2</a></li>
                                <li class="list-inline-item"><a href="#">3</a></li>
                                <li class="list-inline-item"><a href="#">...</a></li>
                                <li class="list-inline-item"><a href="#">15</a></li>
                                <li class="list-inline-item"><a href="#"><i class="fa fa-angle-right"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="fa fa-angle-double-right"></i></a></li>
                            </ul>
                        </div>
                    </div>
                  <div class="col-lg-4 col-md-12">
                <div class="add-widget">
                    <a href="#"><img src="images/add-1.png" alt="" class="img-fluid"></a>
                </div>
                <div class="tab-widget">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#m-view" role="tab">Recent News</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#comment" role="tab">Comments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#catagory" role="tab">Categories</a>
                        </li>
                    </ul>
                    <!-- Tab panes -->


                    <div class="tab-content">

                        <div class="tab-pane fade show active" id="m-view" role="tabpanel">
                            {% for news in latestnews %}
                            <div class="m-view-content">
                            	
                                <div class="m-view-img">
                                    <a href="#"><img src="{{news.image.url}}" alt="" class="img-fluid" style="max-width: 100px!important;"></a>
                                </div>
                                <div class="img-content">
                                    <p><a href="#">{{news.title|safe|truncatewords:"8"}}</a></p>
                                    <ul class="list-unstyled list-inline">
                                        <li class="list-inline-item"><i class="fa fa-star"></i></li>
                                        <li class="list-inline-item"><i class="fa fa-star"></i></li>
                                        <li class="list-inline-item"><i class="fa fa-star"></i></li>
                                        <li class="list-inline-item"><i class="fa fa-star"></i></li>
                                        <li class="list-inline-item"><i class="fa fa-star-o"></i></li>
                                    </ul>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="tab-pane fade" id="comment" role="tabpanel">
                            {% for comment in comments|slice:"5" %}
                            <div class="comment-content">
                                <div class="comment-img">
                                    <a href="#"><i class="fa fa-user"></i></a>
                                </div>
                                <div class="img-content">
                                    <p><a href="#"><span>{{comment.commentername}}:<br></span>{{comment.comment|truncatechars:"50"}}</a></p>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="tab-pane fade" id="catagory" role="tabpanel">
                            <div class="catagory-content">
                                <div class="row">
                                    <div class="col-md-6">
                                        {% for category in categories %}
                                        <ul class="list-unstyled">
                                            <li><a href="#"> {{category.title}} <span>{{category.allnews.count}}</span></a></li> 
                                        </ul>
                                        {% endfor %}
                                    </div>
                                    <div class="col-md-6">
                                        <ul class="list-unstyled">
                                            <li><a href="#">Animal <span>23</span></a></li>
                                            <li><a href="#">Politics <span>27</span></a></li>
                                            <li><a href="#">Health <span>11</span></a></li>
                                            <li><a href="#">National <span>19</span></a></li>
                                            <li><a href="#">Culture <span>21</span></a></li>
                                            <li><a href="#">Music <span>23</span></a></li>
                                            <li><a href="#">Food <span>27</span></a></li>
                                            <li><a href="#">Travel <span>11</span></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="login-widget">
                    <h4>LOG IN</h4>
                    <form method="post">
                        <input type="text" name="name" placeholder="User Name" required>
                        <input type="password" name="password" placeholder="********" required>
                        <label><input type="checkbox" checked="">Remember Me</label>
                        <button type="submit"  value="submit">Log In</button>
                    </form>
                </div>
                <div class="tag-widget">
                    <h4>TAG LIST</h4>
                    <ul class="list-unstyled list-inline">
                        <li class="list-inline-item"><a href="#">News</a></li>
                        <li class="list-inline-item"><a href="#">Article</a></li>
                        <li class="list-inline-item"><a href="#">Online</a></li>
                        <li class="list-inline-item"><a href="#">Tags</a></li>
                        <li class="list-inline-item"><a href="#">World</a></li>
                        <li class="list-inline-item"><a href="#">Google</a></li>
                        <li class="list-inline-item"><a href="#">Wordpress</a></li>
                        <li class="list-inline-item"><a href="#">National</a></li>
                        <li class="list-inline-item"><a href="#">Food</a></li>
                        <li class="list-inline-item"><a href="#">Health</a></li>
                        <li class="list-inline-item"><a href="#">News</a></li>
                        <li class="list-inline-item"><a href="#">Article</a></li>
                        <li class="list-inline-item"><a href="#">Online</a></li>
                        <li class="list-inline-item"><a href="#">Tags</a></li>
                        <li class="list-inline-item"><a href="#">World</a></li>
                        <li class="list-inline-item"><a href="#">Google</a></li>
                        <li class="list-inline-item"><a href="#">Wordpress</a></li>
                        <li class="list-inline-item"><a href="#">National</a></li>
                    </ul>
                </div>
                
            
            </div>
                </div>   
            </div>
        </section>


{% endblock %}



{% for news in category.allnews.all %}

{{news.title}}

{% endfor %}

templates/clienttemplates/newsdetail.html
{% extends 'clienttemplates/base.html' %}
{% load static %}

{% block content %}
{% if messages %}
{% for message in messages %}
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Your comment means us alot..</h4>
      </div>
      <div class="modal-body">
        <p>{{ message }}</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
{% endfor %}
{% endif %}

<section class="p-heading text-center">
        	<div class="container">
        		<div class="page-bg">
        			<div class="row">
        				<div class="col-md-12">
        					<div class="p-content">
        						<h4>{{news.title|truncatechars:"50"}}</h4>
        						<ul class="list-unstyled list-inline">
        							<li class="list-inline-item"><a href="{% url 'sportsnewsapp:home' %}">Home</a></li>
        							<li class="list-inline-item"><i class="fa fa-long-arrow-right"></i>{{news.category}}</li>
        						</ul>
        					</div>
        				</div>
        			</div>
        		</div>
        	</div>
</section>

<!-- News Details -->


<section class="news-details">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12">
                <div class="news-heading">
                    <h4>{{news.title}}</h4>
                    <ul class="list-unstyled list-inline">
                        <li class="list-inline-item"><i class="fa fa-user"></i><a href="#">{{news.author}}</a></li>
                        <li class="list-inline-item"><i class="fa fa-calendar"></i>{{news.created_at.date}}</li>
                        <li class="list-inline-item"><i class="fa fa-comments"></i>(<a href="#">13 Comments</a>)</li>
                        <li class="list-inline-item"><i class="fa fa-eye"></i>{{news.viewed}} times</li>
                    </ul>
                    <img src="{{news.image.url}}" alt="" class="img-fluid">
                    <p>{{news.content|safe}}</p>
                </div>
               
                <div class="row">
                    <div class="col-md-5">
                        <div class="news-tag text-right">
                            <ul class="list-unstyled list-inline">
                                <li class="list-inline-item">TAGS :</li>
                                <li class="list-inline-item"><a href="#">{{news.category}},</a></li>
                                <li class="list-inline-item"><a href="#">{{news.author}},</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="news-author">
                    <img src="images/author.jpg" alt="" class="img-fluid">
                    <h6>AUTHOR: <span>{{news.author}}</span></h6>
                    <p>Anything said by author</p>
                    
                </div>
                <div class="news-comment">
                    <h4>COMMENTS <span>(03)</span></h4>
                    <div class="comment-box d-flex">
                        <div class="comment-img">
                            <img src="images/comment-1.jpg" alt="" class="img-fluid">
                        </div>
                        <div class="img-content">
                            {% for comment in news.comments.all|slice:"5" %}
                            <h6>{{comment.commentername}} {{comment.created_at.date}}</h6>
                            <p>{{comment.comment}}</p>
                            <span><a href="#">Reply</a></span>
                            <br>
                            <br>
                            <br>
                            {% endfor %}
                        </div>
                    </div>
                    
                </div>
                <div class="comment-reply">
                    <h4>LEAVE A COMMENT</h4>
                    
                    <form id="ajax-contact" method="post" action="{% url 'sportsnewsapp:newscommentcreate' news.id %}">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-6">
                                <p>{{form.commentername}}</p>
                             </div>
                            <div class="col-lg-6">
                                <p>{{form.email}}</p>
                            </div>
                            <div class="col-lg-12">
                                <p>{{form.comment}}</p>
                            </div>
                            <div class="col-lg-12">
                                <button type="submit">SUBMIT</button>
                            </div>
                        </div>
                        <div id="form-messages"></div>
                    </form>

                </div>


                <div class="relate-news">
                    <h4>RELATED NEWS</h4>
                    <div class="owl-carousel relate-slider">
                        <div class="slider-content">
                            <img src="images/trending-2.jpg" alt="" class="img-fluid">
                            <div class="slider-layer">
                                <p><a href="#">This handout will help you understand how paragraphs are formed.</a></p>
                                <ul class="list-unstyled list-inline">
                                    <li class="list-inline-item">SPORTS</li>
                                    <li class="list-inline-item">September 24, 2017</li>
                                </ul>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
           
            <div class="col-lg-4 col-md-12">
                <div class="add-widget">
                    <a href="#"><img src="images/add-1.png" alt="" class="img-fluid"></a>
                </div>
                <div class="tab-widget">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#m-view" role="tab">Recent News</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#comment" role="tab">Comments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#catagory" role="tab">Categories</a>
                        </li>
                    </ul>
                    <!-- Tab panes -->


                    <div class="tab-content">

                        <div class="tab-pane fade show active" id="m-view" role="tabpanel">
                            {% for news in latestnews %}
                            <div class="m-view-content">
                            	
                                <div class="m-view-img">
                                    <a href="#"><img src="{{news.image.url}}" alt="" class="img-fluid" style="max-width: 100px!important;"></a>
                                </div>
                                <div class="img-content">
                                    <p><a href="#">{{news.title|safe|truncatewords:"8"}}</a></p>
                                    <ul class="list-unstyled list-inline">
                                        <li class="list-inline-item"><i class="fa fa-star"></i></li>
                                        <li class="list-inline-item"><i class="fa fa-star"></i></li>
                                        <li class="list-inline-item"><i class="fa fa-star"></i></li>
                                        <li class="list-inline-item"><i class="fa fa-star"></i></li>
                                        <li class="list-inline-item"><i class="fa fa-star-o"></i></li>
                                    </ul>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="tab-pane fade" id="comment" role="tabpanel">
                            {% for comment in comments|slice:"5" %}
                            <div class="comment-content">
                                <div class="comment-img">
                                    <a href="#"><i class="fa fa-user"></i></a>
                                </div>
                                <div class="img-content">
                                    <p><a href="#"><span>{{comment.commentername}}:<br></span>{{comment.comment|truncatechars:"50"}}</a></p>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="tab-pane fade" id="catagory" role="tabpanel">
                            <div class="catagory-content">
                                <div class="row">
                                    <div class="col-md-6">
                                        {% for category in categories %}
                                        <ul class="list-unstyled">
                                            <li><a href="#"> {{category.title}} <span>{{category.allnews.count}}</span></a></li> 
                                        </ul>
                                        {% endfor %}
                                    </div>
                                    <div class="col-md-6">
                                        <ul class="list-unstyled">
                                            <li><a href="#">Animal <span>23</span></a></li>
                                            <li><a href="#">Politics <span>27</span></a></li>
                                            <li><a href="#">Health <span>11</span></a></li>
                                            <li><a href="#">National <span>19</span></a></li>
                                            <li><a href="#">Culture <span>21</span></a></li>
                                            <li><a href="#">Music <span>23</span></a></li>
                                            <li><a href="#">Food <span>27</span></a></li>
                                            <li><a href="#">Travel <span>11</span></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="login-widget">
                    <h4>LOG IN</h4>
                    <form method="post">
                        <input type="text" name="name" placeholder="User Name" required>
                        <input type="password" name="password" placeholder="********" required>
                        <label><input type="checkbox" checked="">Remember Me</label>
                        <button type="submit"  value="submit">Log In</button>
                    </form>
                </div>
                <div class="tag-widget">
                    <h4>TAG LIST</h4>
                    <ul class="list-unstyled list-inline">
                        <li class="list-inline-item"><a href="#">News</a></li>
                        <li class="list-inline-item"><a href="#">Article</a></li>
                        <li class="list-inline-item"><a href="#">Online</a></li>
                        <li class="list-inline-item"><a href="#">Tags</a></li>
                        <li class="list-inline-item"><a href="#">World</a></li>
                        <li class="list-inline-item"><a href="#">Google</a></li>
                        <li class="list-inline-item"><a href="#">Wordpress</a></li>
                        <li class="list-inline-item"><a href="#">National</a></li>
                        <li class="list-inline-item"><a href="#">Food</a></li>
                        <li class="list-inline-item"><a href="#">Health</a></li>
                        <li class="list-inline-item"><a href="#">News</a></li>
                        <li class="list-inline-item"><a href="#">Article</a></li>
                        <li class="list-inline-item"><a href="#">Online</a></li>
                        <li class="list-inline-item"><a href="#">Tags</a></li>
                        <li class="list-inline-item"><a href="#">World</a></li>
                        <li class="list-inline-item"><a href="#">Google</a></li>
                        <li class="list-inline-item"><a href="#">Wordpress</a></li>
                        <li class="list-inline-item"><a href="#">National</a></li>
                    </ul>
                </div>
                
            
            </div>
                
        </div>
    </div>
</section>
        <!-- End News Details -->

	


{% endblock %}

{% block js %}
<script type="text/javascript">
    $(window).on('load',function(){
        $('#myModal').modal('show');
    });
</script>

{% endblock js %}